### ISSUE TITLE
Publish apk

### ISSUE THREAD

**Issue by expl0r3r** [tuarua/LibAVANE-Android-Example#1]
I cannot compile the app as screenshot by my AIDE. Could you please publish the full apk?

Thank you very much

**Comment by tuarua** [comment]
Which IDE are you using?
Why can you not compile?
What errors are you getting?

**Comment by expl0r3r** [comment]
I use Android IDE because I don't have PC.
AIDE is not fully support NDK and Gradle. What why I cannot compile the lib mixing ffmpeg and your jni. Or maybe because I don't have many NDK experience.
Therefore, I'd to have the .so files in your apk.

**Comment by tuarua** [comment]
The .so files are included with the repo as one of the submodules.
In any case, if Android IDE doesn't support NDK then you won't be able to build the project. Sorry.
